apiVersion: v1
kind: Service
metadata:
  name: nameservice
spec:
  selector:
    app: nameservice
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: nameservice
  type: LoadBalancer